# Generated by Django 3.2.2 on 2022-02-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('idname', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(default='', max_length=255, null=True)),
                ('lastname', models.CharField(default='', max_length=255, null=True)),
                ('username', models.CharField(default=0, max_length=255, null=True)),
                ('email', models.EmailField(default=0, max_length=254, null=True)),
                ('password', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
    ]
