# Generated by Django 3.2.2 on 2022-03-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('idname', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=255, null=True)),
                ('password', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='signup',
            name='pwd',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
