# Generated by Django 4.0.1 on 2022-04-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0003_designation_user_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='signup',
        ),
    ]
