# Generated by Django 4.0.1 on 2022-04-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0005_remove_user_registration_idproof_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_registration',
            old_name='fullname',
            new_name='firstname',
        ),
        migrations.RemoveField(
            model_name='user_registration',
            name='userid',
        ),
        migrations.AddField(
            model_name='user_registration',
            name='lastname',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
