# Generated by Django 4.0.1 on 2022-04-27 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0007_payment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='messages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='welfare.message'),
        ),
    ]
