# Generated by Django 4.0.1 on 2022-04-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0008_payment_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='messages',
        ),
        migrations.AddField(
            model_name='payment',
            name='message',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='message',
        ),
    ]
