# Generated by Django 4.0.1 on 2022-04-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0009_remove_payment_messages_payment_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_registration',
            old_name='joiningdate',
            new_name='date',
        ),
        migrations.AddField(
            model_name='user_registration',
            name='message',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='payment',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='payment',
        ),
    ]
