# Generated by Django 4.0.1 on 2022-04-27 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0010_rename_joiningdate_user_registration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_registration',
            name='message',
        ),
        migrations.RemoveField(
            model_name='user_registration',
            name='payment',
        ),
        migrations.CreateModel(
            name='doner_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=240, null=True)),
                ('lastname', models.CharField(max_length=240, null=True)),
                ('pincode', models.CharField(max_length=240, null=True)),
                ('country', models.CharField(max_length=240, null=True)),
                ('permanentaddress1', models.CharField(max_length=240, null=True)),
                ('permanentaddress2', models.CharField(max_length=240, null=True)),
                ('mobile', models.CharField(max_length=240, null=True)),
                ('email', models.EmailField(max_length=240, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('payment', models.EmailField(max_length=240, null=True)),
                ('message', models.EmailField(max_length=240, null=True)),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='welfare.designation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='welfare.user_registration')),
            ],
        ),
    ]
