# Generated by Django 4.0.1 on 2022-04-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0011_remove_user_registration_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doner_registration',
            name='user',
        ),
    ]
