# Generated by Django 4.0.1 on 2022-04-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0012_remove_doner_registration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doner_registration',
            name='status',
            field=models.CharField(default='', max_length=240, null=True),
        ),
    ]
