# Generated by Django 4.0.1 on 2022-04-29 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0016_message_admin_replay_message_admin_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message_admin',
            name='status',
        ),
    ]
