# Generated by Django 4.0.1 on 2022-04-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0017_remove_message_admin_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='username',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
