# Generated by Django 4.0.1 on 2022-05-02 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0019_restaurant_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant_registration',
            name='status',
        ),
        migrations.CreateModel(
            name='request_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=240, null=True)),
                ('location', models.CharField(max_length=240, null=True)),
                ('mobile', models.CharField(max_length=240, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('quantity', models.CharField(default='', max_length=240, null=True)),
                ('restaurantname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='welfare.restaurant_registration')),
            ],
        ),
    ]
