# Generated by Django 4.0.1 on 2022-05-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0022_request_food_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_food',
            name='time',
        ),
    ]
