# Generated by Django 4.0.1 on 2022-05-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0023_remove_request_food_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_food',
            name='cookedtime',
            field=models.CharField(default='', max_length=240, null=True),
        ),
    ]
