# Generated by Django 4.0.1 on 2022-05-05 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0024_request_food_cookedtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='doner_registration',
            name='duser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='welfare.user_registration'),
        ),
    ]
