# Generated by Django 4.0.1 on 2022-05-05 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0025_doner_registration_duser'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_admin',
            name='donuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='welfare.doner_registration'),
        ),
    ]
